### ISSUE TITLE
Support for cd_files

### ISSUE THREAD

**Issue by jfpanisset** [eaksel/packer-Win2019#3]
Thank you for a very useful project, I was able to use it as a great source of information to build Windows 2019 images using the hyperv-iso and hyperv-vmcx builders. 

Packer 1.6.3 added support for the [cd_files ](https://www.packer.io/docs/builders/virtualbox/iso#optional-4) token to a number of builders, including the virtualbox-iso one.
This allows you to specify a list of files which Packer will package up as an ISO and attach to the booting VM. For instance it can make it more convenient to make changes to autounattend.xml without having to rewrap it into an ISO, and is an alternative to the floppy_files token on platforms where a virtual floppy drive is no longer supported (for instance Generation 2 VMs on Hyper-V).

The drawback is that you need one of the supported command line ISO authoring utilities in the path, oscdimg.exe can be extracted from the [Windows 10 ADK](https://docs.microsoft.com/en-us/windows-hardware/get-started/adk-install).

**Comment by eaksel** [comment]
Hi @jfpanisset,

I'm glad you're enjoying it. 
Thanks for letting me know about this new feature, I haven't been following packer lately and wasn't aware of it.

It does look appealing, however the fact that you have get oscdimg.exe from the ADK that has a non-negligible size and that you have to add it to your path, would in my opinion deter a lot of people from using these packer files. I've tried looking for info about whether or not I could redistribute oscdimg.exe, but I haven't found anything.
As for linux users, they'd still have to add one of the .iso generating tools to their path.

This is why I prefer not to switch to using the cd_files parameter.

If you'd like to, you can send a PR to add your Hyper-V builder with cd_files, and as it is the only supported way for using autounattend.xml files on gen 2 VMs I'd be more than glad to merge it.
