### ISSUE TITLE
Packer build gets stuck on waiting for WinRM to become available when set-edition set to StandardServer instead of Datacenter

### ISSUE THREAD

**Issue by ghost** [eaksel/packer-Win2019#4]
Hi 

Thanks for the awesome project and for your work

I am trying to build ServerStandard edition instead of Datacenter one so I changed the scripts/bios/gui/autounattend.xml file like below :

   ```
<SynchronousCommand wcm:action="add">
                    <CommandLine>%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -Command dism /online /quiet /set-edition:ServerStandard /productkey:N69G4-B89J2-4G8F4-WWYCC-J464C /accepteula</CommandLine>
                    <Order>7</Order>
                    <Description>Switch from EVAL to VL</Description>
     </SynchronousCommand>
```

When I try to build the image, it gets stuck waiting for WinRM to become available and never proceeds further.

I got the product key from Microsoft's official KSM activation page for Win2k19 StandardServer Edition.

https://docs.microsoft.com/en-us/windows-server/get-started/kmsclientkeys

I am using VMWare Workstation PRO to build the image via below command

`packer build -only=vmware-iso win2019-gui.json
`
Do you have any insights what might be the culprit or what should I change else in the configuration files to make this work?

Thank you

**Comment by eaksel** [comment]
Hi @aydintd,

I've just tried doing the same and it worked on fine for me.
My first guess is that there might be a typo in your 'scripts/bios/gui/autounattend.xml' file. Can you compare it with the one I've attached, and see if there's any difference ? (I had to change the file ext to be able to attach it)
[autounattend.txt](https://github.com/eaksel/packer-Win2019/files/6409325/autounattend.txt)

To confirm whether you have switched to Server Standard mode or not you can got to:
Settings > Update & Security > Activation
And check if the edition is 'Standard', or 'Standard Evaluation'.
Alternatively you can use the command 'slmgr /dli' and check if it says 'ServerStandard' or 'ServerStandardEval'.

If all of the above is fine, then you should check if you have network connectivity between your VMware host and the VM. (If the build worked before you edited the file, then this is probably not the issue).

Let me know if you manage to find out what was causing the issue.

**Comment by ghost** [comment]
Hi @eaksel 

I managed to workaround this by removing the below stop WinRM service command before the dism /online /set-edition:ServerStandard command and it got through and generated the vmdk image afterwards :

```
     <SynchronousCommand wcm:action="add">
                    <CommandLine>%SystemRoot%\system32\WindowsPowerShell\v1.0\powershell.exe -Command Stop-Service WinRM</CommandLine>
                    <Description>Stop the WinRM service to allow the dism process to finish before packer executes scripts</Description>
                    <Order>6</Order>
                    <RequiresUserInput>true</RequiresUserInput>
                </SynchronousCommand>
```

I will try out the autounattend.xml file that you've shared and let you know,

Thank you for taking a look onto this, highly appreciated.

**Comment by ghost** [comment]
Hi Emre,

Thank you for providing the autounattend.xml file again, it got through this time without removing the winrm stop service command from the file. As you've mentioned I probably had a typo, invisible to my eyes in my version which was preventing me to complete the image build.

It might be a good idea to mention how people can generate Standard server editions by using your project in the README.md file, just a suggestion! :-)

I will help myself and close out this issue.
